/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 77
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 23
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__bodiless_method = 1,
  sym__body_method = 2,
  sym_url_text = 3,
  sym_version = 4,
  aux_sym_trailer_token1 = 5,
  anon_sym_COLON = 6,
  sym_header_name = 7,
  sym_plain = 8,
  sym_status_code = 9,
  sym__body_head = 10,
  sym__terminal_line = 11,
  sym_value_text = 12,
  sym__ws = 13,
  sym__blank = 14,
  sym__eol = 15,
  sym_document = 16,
  sym__item = 17,
  sym_request = 18,
  sym__bodiless_request = 19,
  sym__body_request = 20,
  sym__request_line = 21,
  sym_target = 22,
  sym_trailer = 23,
  sym_header = 24,
  sym_response = 25,
  sym__status_line_tail = 26,
  sym_status_text = 27,
  sym_body = 28,
  sym_value = 29,
  aux_sym_document_repeat1 = 30,
  aux_sym__bodiless_request_repeat1 = 31,
  aux_sym__body_request_repeat1 = 32,
  aux_sym_body_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__bodiless_method] = "method",
  [sym__body_method] = "method",
  [sym_url_text] = "url_text",
  [sym_version] = "version",
  [aux_sym_trailer_token1] = "trailer_token1",
  [anon_sym_COLON] = ":",
  [sym_header_name] = "header_name",
  [sym_plain] = "plain",
  [sym_status_code] = "status_code",
  [sym__body_head] = "_body_head",
  [sym__terminal_line] = "_terminal_line",
  [sym_value_text] = "value_text",
  [sym__ws] = "_ws",
  [sym__blank] = "_blank",
  [sym__eol] = "_eol",
  [sym_document] = "document",
  [sym__item] = "_item",
  [sym_request] = "request",
  [sym__bodiless_request] = "_bodiless_request",
  [sym__body_request] = "_body_request",
  [sym__request_line] = "_request_line",
  [sym_target] = "target",
  [sym_trailer] = "trailer",
  [sym_header] = "header",
  [sym_response] = "response",
  [sym__status_line_tail] = "_status_line_tail",
  [sym_status_text] = "status_text",
  [sym_body] = "body",
  [sym_value] = "value",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym__bodiless_request_repeat1] = "_bodiless_request_repeat1",
  [aux_sym__body_request_repeat1] = "_body_request_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__bodiless_method] = sym__bodiless_method,
  [sym__body_method] = sym__bodiless_method,
  [sym_url_text] = sym_url_text,
  [sym_version] = sym_version,
  [aux_sym_trailer_token1] = aux_sym_trailer_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_header_name] = sym_header_name,
  [sym_plain] = sym_plain,
  [sym_status_code] = sym_status_code,
  [sym__body_head] = sym__body_head,
  [sym__terminal_line] = sym__terminal_line,
  [sym_value_text] = sym_value_text,
  [sym__ws] = sym__ws,
  [sym__blank] = sym__blank,
  [sym__eol] = sym__eol,
  [sym_document] = sym_document,
  [sym__item] = sym__item,
  [sym_request] = sym_request,
  [sym__bodiless_request] = sym__bodiless_request,
  [sym__body_request] = sym__body_request,
  [sym__request_line] = sym__request_line,
  [sym_target] = sym_target,
  [sym_trailer] = sym_trailer,
  [sym_header] = sym_header,
  [sym_response] = sym_response,
  [sym__status_line_tail] = sym__status_line_tail,
  [sym_status_text] = sym_status_text,
  [sym_body] = sym_body,
  [sym_value] = sym_value,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym__bodiless_request_repeat1] = aux_sym__bodiless_request_repeat1,
  [aux_sym__body_request_repeat1] = aux_sym__body_request_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__bodiless_method] = {
    .visible = true,
    .named = true,
  },
  [sym__body_method] = {
    .visible = true,
    .named = true,
  },
  [sym_url_text] = {
    .visible = true,
    .named = true,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_trailer_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_header_name] = {
    .visible = true,
    .named = true,
  },
  [sym_plain] = {
    .visible = true,
    .named = true,
  },
  [sym_status_code] = {
    .visible = true,
    .named = true,
  },
  [sym__body_head] = {
    .visible = false,
    .named = true,
  },
  [sym__terminal_line] = {
    .visible = false,
    .named = true,
  },
  [sym_value_text] = {
    .visible = true,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [sym__blank] = {
    .visible = false,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_request] = {
    .visible = true,
    .named = true,
  },
  [sym__bodiless_request] = {
    .visible = false,
    .named = true,
  },
  [sym__body_request] = {
    .visible = false,
    .named = true,
  },
  [sym__request_line] = {
    .visible = false,
    .named = true,
  },
  [sym_target] = {
    .visible = true,
    .named = true,
  },
  [sym_trailer] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_response] = {
    .visible = true,
    .named = true,
  },
  [sym__status_line_tail] = {
    .visible = false,
    .named = true,
  },
  [sym_status_text] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__bodiless_request_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__body_request_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_method = 2,
  field_name = 3,
  field_reason = 4,
  field_status = 5,
  field_target = 6,
  field_value = 7,
  field_version = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_method] = "method",
  [field_name] = "name",
  [field_reason] = "reason",
  [field_status] = "status",
  [field_target] = "target",
  [field_value] = "value",
  [field_version] = "version",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 4},
  [3] = {.index = 7, .length = 1},
  [4] = {.index = 8, .length = 3},
  [5] = {.index = 11, .length = 1},
  [6] = {.index = 12, .length = 1},
  [7] = {.index = 13, .length = 3},
  [8] = {.index = 16, .length = 1},
  [9] = {.index = 17, .length = 2},
  [10] = {.index = 19, .length = 2},
  [11] = {.index = 21, .length = 1},
  [12] = {.index = 22, .length = 4},
  [13] = {.index = 26, .length = 1},
  [14] = {.index = 27, .length = 2},
  [15] = {.index = 29, .length = 2},
  [16] = {.index = 31, .length = 4},
  [17] = {.index = 35, .length = 2},
  [18] = {.index = 37, .length = 4},
  [19] = {.index = 41, .length = 2},
  [20] = {.index = 43, .length = 4},
  [21] = {.index = 47, .length = 2},
  [22] = {.index = 49, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_method, 0, .inherited = true},
    {field_target, 0, .inherited = true},
    {field_version, 0, .inherited = true},
  [3] =
    {field_body, 0, .inherited = true},
    {field_method, 0, .inherited = true},
    {field_target, 0, .inherited = true},
    {field_version, 0, .inherited = true},
  [7] =
    {field_version, 0},
  [8] =
    {field_method, 0},
    {field_target, 2, .inherited = true},
    {field_version, 2, .inherited = true},
  [11] =
    {field_status, 1},
  [12] =
    {field_reason, 1},
  [13] =
    {field_reason, 1, .inherited = true},
    {field_status, 1, .inherited = true},
    {field_version, 0},
  [16] =
    {field_target, 0},
  [17] =
    {field_body, 3},
    {field_version, 0},
  [19] =
    {field_reason, 2},
    {field_status, 1},
  [21] =
    {field_reason, 2},
  [22] =
    {field_body, 4},
    {field_method, 0},
    {field_target, 2, .inherited = true},
    {field_version, 2, .inherited = true},
  [26] =
    {field_name, 0},
  [27] =
    {field_body, 4},
    {field_version, 0},
  [29] =
    {field_reason, 3},
    {field_status, 1},
  [31] =
    {field_body, 4},
    {field_reason, 1, .inherited = true},
    {field_status, 1, .inherited = true},
    {field_version, 0},
  [35] =
    {field_target, 0},
    {field_version, 2},
  [37] =
    {field_body, 5},
    {field_method, 0},
    {field_target, 2, .inherited = true},
    {field_version, 2, .inherited = true},
  [41] =
    {field_name, 0},
    {field_value, 2},
  [43] =
    {field_body, 5},
    {field_reason, 1, .inherited = true},
    {field_status, 1, .inherited = true},
    {field_version, 0},
  [47] =
    {field_name, 0},
    {field_value, 3},
  [49] =
    {field_name, 0},
    {field_value, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(51);
      ADVANCE_MAP(
        '\n', 138,
        '\r', 139,
        ':', 211,
        'H', 143,
        'h', 153,
        '\t', 180,
        ' ', 180,
        'C', 164,
        'c', 164,
        'D', 154,
        'd', 154,
        'G', 155,
        'g', 155,
        'O', 166,
        'o', 166,
        'P', 147,
        'p', 147,
        'T', 167,
        't', 167,
        0x0b, 211,
        '\f', 211,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(174);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(214);
      if (lookahead == '\r') ADVANCE(215);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(214);
      if (lookahead == '\r') ADVANCE(215);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(214);
      if (lookahead == '\r') ADVANCE(215);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(137);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(44);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(62);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(213);
      END_STATE();
    case 7:
      if (lookahead == 'H') ADVANCE(59);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(61);
      END_STATE();
    case 8:
      if (lookahead == 'P') ADVANCE(5);
      END_STATE();
    case 9:
      if (lookahead == 'T') ADVANCE(10);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'T') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(213);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(100);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(61);
      END_STATE();
    case 12:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(213);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(61);
      END_STATE();
    case 13:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(213);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(212);
      END_STATE();
    case 14:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(41);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(38);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(42);
      END_STATE();
    case 17:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(39);
      END_STATE();
    case 18:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 19:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(24);
      END_STATE();
    case 20:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(52);
      END_STATE();
    case 21:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 22:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 23:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 24:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 25:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 26:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 27:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(53);
      END_STATE();
    case 28:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 29:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 30:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 31:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 32:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 33:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 34:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 35:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(40);
      END_STATE();
    case 36:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 37:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(52);
      END_STATE();
    case 38:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(42);
      END_STATE();
    case 39:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(52);
      END_STATE();
    case 40:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(28);
      END_STATE();
    case 41:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(18);
      END_STATE();
    case 42:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(53);
      END_STATE();
    case 43:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(24);
      END_STATE();
    case 44:
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 45:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(54);
      END_STATE();
    case 46:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(212);
      END_STATE();
    case 47:
      if (eof) ADVANCE(51);
      ADVANCE_MAP(
        '\n', 138,
        '\r', 139,
        'H', 178,
        'h', 189,
        '\t', 180,
        ' ', 180,
        'C', 200,
        'c', 200,
        'D', 190,
        'd', 190,
        'G', 191,
        'g', 191,
        'O', 202,
        'o', 202,
        'P', 183,
        'p', 183,
        'T', 203,
        't', 203,
      );
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 48:
      if (eof) ADVANCE(51);
      ADVANCE_MAP(
        '\n', 214,
        '\r', 215,
        ':', 62,
        'H', 9,
        'h', 21,
        '\t', 1,
        ' ', 1,
        'C', 33,
        'c', 33,
        'D', 22,
        'd', 22,
        'G', 23,
        'g', 23,
        'O', 35,
        'o', 35,
        'P', 16,
        'p', 16,
        'T', 36,
        't', 36,
      );
      END_STATE();
    case 49:
      if (eof) ADVANCE(51);
      ADVANCE_MAP(
        '\n', 214,
        '\r', 215,
        'H', 65,
        'h', 75,
        '\t', 2,
        ' ', 2,
        'C', 86,
        'c', 86,
        'D', 76,
        'd', 76,
        'G', 77,
        'g', 77,
        'O', 88,
        'o', 88,
        'P', 69,
        'p', 69,
        'T', 89,
        't', 89,
      );
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 50:
      if (eof) ADVANCE(51);
      ADVANCE_MAP(
        '\n', 214,
        '\r', 215,
        'H', 105,
        'h', 115,
        '\t', 3,
        ' ', 3,
        'C', 126,
        'c', 126,
        'D', 116,
        'd', 116,
        'G', 117,
        'g', 117,
        'O', 128,
        'o', 128,
        'P', 109,
        'p', 109,
        'T', 129,
        't', 129,
      );
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(137);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__bodiless_method);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__body_method);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_url_text);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_version);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_trailer_token1);
      if (lookahead == '/') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(61);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_trailer_token1);
      if (lookahead == 'P') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(61);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_trailer_token1);
      if (lookahead == 'T') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(61);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_trailer_token1);
      if (lookahead == 'T') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(61);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_trailer_token1);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(61);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_trailer_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == '/') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'P') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'T') ADVANCE(66);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'T') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_header_name);
      ADVANCE_MAP(
        '\n', 98,
        '\r', 99,
        'A', 94,
        'a', 94,
        'O', 91,
        'o', 91,
        'U', 92,
        'u', 92,
      );
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (lookahead != 0 &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(97);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(97);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_plain);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_plain);
      if (lookahead == '\n') ADVANCE(98);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_status_code);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym__body_head);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == '/') ADVANCE(136);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'P') ADVANCE(103);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'T') ADVANCE(106);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(107);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'T') ADVANCE(104);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(113);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(112);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym__body_head);
      ADVANCE_MAP(
        '\n', 101,
        '\r', 102,
        'A', 134,
        'a', 134,
        'O', 131,
        'o', 131,
        'U', 132,
        'u', 132,
      );
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(132);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(120);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(114);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(137);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(137);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(107);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(122);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(132);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(110);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(135);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(137);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(127);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(119);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(125);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(130);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(118);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(123);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(124);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(133);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(108);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(137);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(132);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(137);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(121);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(111);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(114);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(136);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym__body_head);
      if (lookahead == '\n') ADVANCE(101);
      if (lookahead == '\r') ADVANCE(102);
      if (lookahead != 0) ADVANCE(137);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym__terminal_line);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == '/') ADVANCE(175);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == '/') ADVANCE(210);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'P') ADVANCE(140);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'T') ADVANCE(144);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(145);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'T') ADVANCE(142);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(151);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(150);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym__terminal_line);
      ADVANCE_MAP(
        '\n', 138,
        '\r', 139,
        ':', 211,
        'A', 172,
        'a', 172,
        'O', 169,
        'o', 169,
        'U', 170,
        'u', 170,
      );
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(170);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(158);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(152);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(176);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(176);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(145);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(160);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(170);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(148);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(173);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(176);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(165);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(157);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(163);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(168);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(156);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(161);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(162);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(171);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(146);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(176);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(170);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(176);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(159);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(149);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(152);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(174);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(175);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead != 0) ADVANCE(176);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'P') ADVANCE(141);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'T') ADVANCE(179);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(181);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'T') ADVANCE(177);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(180);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(187);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(186);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym__terminal_line);
      ADVANCE_MAP(
        '\n', 138,
        '\r', 139,
        'A', 208,
        'a', 208,
        'O', 205,
        'o', 205,
        'U', 206,
        'u', 206,
      );
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(206);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(194);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(188);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(211);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(211);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(181);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(196);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(206);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(184);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(209);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(211);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(201);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(193);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(199);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(204);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(192);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(197);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(198);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(207);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(182);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(211);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(206);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(211);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(195);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(185);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(188);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(210);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(sym__terminal_line);
      if (lookahead == '\n') ADVANCE(138);
      if (lookahead == '\r') ADVANCE(139);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(sym_value_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(212);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(213);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(sym__blank);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(sym__blank);
      if (lookahead == '\n') ADVANCE(214);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 48},
  [2] = {.lex_state = 48},
  [3] = {.lex_state = 48},
  [4] = {.lex_state = 49},
  [5] = {.lex_state = 49},
  [6] = {.lex_state = 49},
  [7] = {.lex_state = 49},
  [8] = {.lex_state = 49},
  [9] = {.lex_state = 49},
  [10] = {.lex_state = 49},
  [11] = {.lex_state = 49},
  [12] = {.lex_state = 49},
  [13] = {.lex_state = 50},
  [14] = {.lex_state = 50},
  [15] = {.lex_state = 50},
  [16] = {.lex_state = 50},
  [17] = {.lex_state = 50},
  [18] = {.lex_state = 50},
  [19] = {.lex_state = 47},
  [20] = {.lex_state = 50},
  [21] = {.lex_state = 49},
  [22] = {.lex_state = 47},
  [23] = {.lex_state = 49},
  [24] = {.lex_state = 49},
  [25] = {.lex_state = 49},
  [26] = {.lex_state = 49},
  [27] = {.lex_state = 49},
  [28] = {.lex_state = 47},
  [29] = {.lex_state = 49},
  [30] = {.lex_state = 49},
  [31] = {.lex_state = 49},
  [32] = {.lex_state = 49},
  [33] = {.lex_state = 49},
  [34] = {.lex_state = 49},
  [35] = {.lex_state = 48},
  [36] = {.lex_state = 48},
  [37] = {.lex_state = 48},
  [38] = {.lex_state = 48},
  [39] = {.lex_state = 48},
  [40] = {.lex_state = 48},
  [41] = {.lex_state = 11, .external_lex_state = 1},
  [42] = {.lex_state = 48},
  [43] = {.lex_state = 48},
  [44] = {.lex_state = 13, .external_lex_state = 1},
  [45] = {.lex_state = 7, .external_lex_state = 1},
  [46] = {.lex_state = 12, .external_lex_state = 1},
  [47] = {.lex_state = 13, .external_lex_state = 1},
  [48] = {.lex_state = 46, .external_lex_state = 1},
  [49] = {.lex_state = 45},
  [50] = {.lex_state = 46, .external_lex_state = 1},
  [51] = {.lex_state = 45},
  [52] = {.lex_state = 11, .external_lex_state = 1},
  [53] = {.lex_state = 11, .external_lex_state = 1},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 12},
  [56] = {.lex_state = 11, .external_lex_state = 1},
  [57] = {.lex_state = 11, .external_lex_state = 1},
  [58] = {.lex_state = 11, .external_lex_state = 1},
  [59] = {.lex_state = 12},
  [60] = {.lex_state = 11, .external_lex_state = 1},
  [61] = {.lex_state = 0, .external_lex_state = 1},
  [62] = {.lex_state = 0, .external_lex_state = 1},
  [63] = {.lex_state = 0, .external_lex_state = 1},
  [64] = {.lex_state = 11},
  [65] = {.lex_state = 0, .external_lex_state = 1},
  [66] = {.lex_state = 0, .external_lex_state = 1},
  [67] = {.lex_state = 11},
  [68] = {.lex_state = 0, .external_lex_state = 1},
  [69] = {.lex_state = 0, .external_lex_state = 1},
  [70] = {.lex_state = 0, .external_lex_state = 1},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0, .external_lex_state = 1},
  [73] = {.lex_state = 48},
  [74] = {.lex_state = 0, .external_lex_state = 1},
  [75] = {.lex_state = 0, .external_lex_state = 1},
  [76] = {.lex_state = 0, .external_lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__bodiless_method] = ACTIONS(1),
    [sym__body_method] = ACTIONS(1),
    [sym_version] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_header_name] = ACTIONS(1),
    [sym_status_code] = ACTIONS(1),
    [sym__terminal_line] = ACTIONS(1),
    [sym__ws] = ACTIONS(1),
    [sym__blank] = ACTIONS(1),
    [sym__eol] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(71),
    [sym__item] = STATE(2),
    [sym_request] = STATE(2),
    [sym__bodiless_request] = STATE(37),
    [sym__body_request] = STATE(38),
    [sym_response] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__bodiless_method] = ACTIONS(5),
    [sym__body_method] = ACTIONS(7),
    [sym_version] = ACTIONS(9),
    [sym__blank] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      sym__bodiless_method,
    ACTIONS(7), 1,
      sym__body_method,
    ACTIONS(9), 1,
      sym_version,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym__blank,
    STATE(37), 1,
      sym__bodiless_request,
    STATE(38), 1,
      sym__body_request,
    STATE(3), 4,
      sym__item,
      sym_request,
      sym_response,
      aux_sym_document_repeat1,
  [28] = 8,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym__bodiless_method,
    ACTIONS(22), 1,
      sym__body_method,
    ACTIONS(25), 1,
      sym_version,
    ACTIONS(28), 1,
      sym__blank,
    STATE(37), 1,
      sym__bodiless_request,
    STATE(38), 1,
      sym__body_request,
    STATE(3), 4,
      sym__item,
      sym_request,
      sym_response,
      aux_sym_document_repeat1,
  [56] = 7,
    ACTIONS(35), 1,
      sym_header_name,
    ACTIONS(37), 1,
      sym_plain,
    ACTIONS(39), 1,
      sym__blank,
    STATE(13), 1,
      aux_sym__body_request_repeat1,
    ACTIONS(31), 2,
      ts_builtin_sym_end,
      sym_version,
    ACTIONS(33), 2,
      sym__bodiless_method,
      sym__body_method,
    STATE(5), 2,
      sym_header,
      aux_sym__bodiless_request_repeat1,
  [81] = 7,
    ACTIONS(35), 1,
      sym_header_name,
    ACTIONS(45), 1,
      sym_plain,
    ACTIONS(47), 1,
      sym__blank,
    STATE(18), 1,
      aux_sym__body_request_repeat1,
    ACTIONS(41), 2,
      ts_builtin_sym_end,
      sym_version,
    ACTIONS(43), 2,
      sym__bodiless_method,
      sym__body_method,
    STATE(12), 2,
      sym_header,
      aux_sym__bodiless_request_repeat1,
  [106] = 7,
    ACTIONS(35), 1,
      sym_header_name,
    ACTIONS(53), 1,
      sym_plain,
    ACTIONS(55), 1,
      sym__blank,
    STATE(14), 1,
      aux_sym__body_request_repeat1,
    ACTIONS(49), 2,
      ts_builtin_sym_end,
      sym_version,
    ACTIONS(51), 2,
      sym__bodiless_method,
      sym__body_method,
    STATE(9), 2,
      sym_header,
      aux_sym__bodiless_request_repeat1,
  [131] = 7,
    ACTIONS(35), 1,
      sym_header_name,
    ACTIONS(61), 1,
      sym_plain,
    ACTIONS(63), 1,
      sym__blank,
    STATE(15), 1,
      aux_sym__body_request_repeat1,
    ACTIONS(57), 2,
      ts_builtin_sym_end,
      sym_version,
    ACTIONS(59), 2,
      sym__bodiless_method,
      sym__body_method,
    STATE(8), 2,
      sym_header,
      aux_sym__bodiless_request_repeat1,
  [156] = 7,
    ACTIONS(35), 1,
      sym_header_name,
    ACTIONS(45), 1,
      sym_plain,
    ACTIONS(69), 1,
      sym__blank,
    STATE(17), 1,
      aux_sym__body_request_repeat1,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      sym_version,
    ACTIONS(67), 2,
      sym__bodiless_method,
      sym__body_method,
    STATE(12), 2,
      sym_header,
      aux_sym__bodiless_request_repeat1,
  [181] = 7,
    ACTIONS(35), 1,
      sym_header_name,
    ACTIONS(45), 1,
      sym_plain,
    ACTIONS(75), 1,
      sym__blank,
    STATE(16), 1,
      aux_sym__body_request_repeat1,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      sym_version,
    ACTIONS(73), 2,
      sym__bodiless_method,
      sym__body_method,
    STATE(12), 2,
      sym_header,
      aux_sym__bodiless_request_repeat1,
  [206] = 5,
    ACTIONS(35), 1,
      sym_header_name,
    ACTIONS(81), 1,
      sym_plain,
    ACTIONS(79), 2,
      sym__bodiless_method,
      sym__body_method,
    STATE(11), 2,
      sym_header,
      aux_sym__bodiless_request_repeat1,
    ACTIONS(77), 3,
      ts_builtin_sym_end,
      sym_version,
      sym__blank,
  [226] = 5,
    ACTIONS(35), 1,
      sym_header_name,
    ACTIONS(45), 1,
      sym_plain,
    ACTIONS(85), 2,
      sym__bodiless_method,
      sym__body_method,
    STATE(12), 2,
      sym_header,
      aux_sym__bodiless_request_repeat1,
    ACTIONS(83), 3,
      ts_builtin_sym_end,
      sym_version,
      sym__blank,
  [246] = 5,
    ACTIONS(91), 1,
      sym_header_name,
    ACTIONS(94), 1,
      sym_plain,
    ACTIONS(89), 2,
      sym__bodiless_method,
      sym__body_method,
    STATE(12), 2,
      sym_header,
      aux_sym__bodiless_request_repeat1,
    ACTIONS(87), 3,
      ts_builtin_sym_end,
      sym_version,
      sym__blank,
  [266] = 6,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 1,
      sym__body_head,
    ACTIONS(99), 1,
      sym__blank,
    STATE(20), 1,
      aux_sym__body_request_repeat1,
    STATE(36), 1,
      sym_body,
    ACTIONS(43), 3,
      sym__bodiless_method,
      sym__body_method,
      sym_version,
  [287] = 6,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 1,
      sym__body_head,
    ACTIONS(99), 1,
      sym__blank,
    STATE(20), 1,
      aux_sym__body_request_repeat1,
    STATE(39), 1,
      sym_body,
    ACTIONS(73), 3,
      sym__bodiless_method,
      sym__body_method,
      sym_version,
  [308] = 6,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 1,
      sym__body_head,
    ACTIONS(99), 1,
      sym__blank,
    STATE(20), 1,
      aux_sym__body_request_repeat1,
    STATE(43), 1,
      sym_body,
    ACTIONS(67), 3,
      sym__bodiless_method,
      sym__body_method,
      sym_version,
  [329] = 6,
    ACTIONS(97), 1,
      sym__body_head,
    ACTIONS(99), 1,
      sym__blank,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      aux_sym__body_request_repeat1,
    STATE(42), 1,
      sym_body,
    ACTIONS(103), 3,
      sym__bodiless_method,
      sym__body_method,
      sym_version,
  [350] = 6,
    ACTIONS(97), 1,
      sym__body_head,
    ACTIONS(99), 1,
      sym__blank,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      aux_sym__body_request_repeat1,
    STATE(35), 1,
      sym_body,
    ACTIONS(107), 3,
      sym__bodiless_method,
      sym__body_method,
      sym_version,
  [371] = 6,
    ACTIONS(97), 1,
      sym__body_head,
    ACTIONS(99), 1,
      sym__blank,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      aux_sym__body_request_repeat1,
    STATE(40), 1,
      sym_body,
    ACTIONS(111), 3,
      sym__bodiless_method,
      sym__body_method,
      sym_version,
  [392] = 4,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    ACTIONS(117), 1,
      sym__terminal_line,
    STATE(19), 1,
      aux_sym_body_repeat1,
    ACTIONS(115), 4,
      sym__bodiless_method,
      sym__body_method,
      sym_version,
      sym__blank,
  [408] = 4,
    ACTIONS(124), 1,
      sym__blank,
    STATE(20), 1,
      aux_sym__body_request_repeat1,
    ACTIONS(120), 2,
      ts_builtin_sym_end,
      sym__body_head,
    ACTIONS(122), 3,
      sym__bodiless_method,
      sym__body_method,
      sym_version,
  [424] = 2,
    ACTIONS(127), 3,
      ts_builtin_sym_end,
      sym_version,
      sym__blank,
    ACTIONS(129), 4,
      sym__bodiless_method,
      sym__body_method,
      sym_header_name,
      sym_plain,
  [436] = 4,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    ACTIONS(135), 1,
      sym__terminal_line,
    STATE(19), 1,
      aux_sym_body_repeat1,
    ACTIONS(133), 4,
      sym__bodiless_method,
      sym__body_method,
      sym_version,
      sym__blank,
  [452] = 2,
    ACTIONS(137), 3,
      ts_builtin_sym_end,
      sym_version,
      sym__blank,
    ACTIONS(139), 4,
      sym__bodiless_method,
      sym__body_method,
      sym_header_name,
      sym_plain,
  [464] = 2,
    ACTIONS(141), 3,
      ts_builtin_sym_end,
      sym_version,
      sym__blank,
    ACTIONS(143), 4,
      sym__bodiless_method,
      sym__body_method,
      sym_header_name,
      sym_plain,
  [476] = 2,
    ACTIONS(145), 3,
      ts_builtin_sym_end,
      sym_version,
      sym__blank,
    ACTIONS(147), 4,
      sym__bodiless_method,
      sym__body_method,
      sym_header_name,
      sym_plain,
  [488] = 2,
    ACTIONS(149), 3,
      ts_builtin_sym_end,
      sym_version,
      sym__blank,
    ACTIONS(151), 4,
      sym__bodiless_method,
      sym__body_method,
      sym_header_name,
      sym_plain,
  [500] = 2,
    ACTIONS(153), 3,
      ts_builtin_sym_end,
      sym_version,
      sym__blank,
    ACTIONS(155), 4,
      sym__bodiless_method,
      sym__body_method,
      sym_header_name,
      sym_plain,
  [512] = 4,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    ACTIONS(161), 1,
      sym__terminal_line,
    STATE(22), 1,
      aux_sym_body_repeat1,
    ACTIONS(159), 4,
      sym__bodiless_method,
      sym__body_method,
      sym_version,
      sym__blank,
  [528] = 2,
    ACTIONS(163), 3,
      ts_builtin_sym_end,
      sym_version,
      sym__blank,
    ACTIONS(165), 4,
      sym__bodiless_method,
      sym__body_method,
      sym_header_name,
      sym_plain,
  [540] = 2,
    ACTIONS(167), 3,
      ts_builtin_sym_end,
      sym_version,
      sym__blank,
    ACTIONS(169), 4,
      sym__bodiless_method,
      sym__body_method,
      sym_header_name,
      sym_plain,
  [552] = 2,
    ACTIONS(171), 3,
      ts_builtin_sym_end,
      sym_version,
      sym__blank,
    ACTIONS(173), 4,
      sym__bodiless_method,
      sym__body_method,
      sym_header_name,
      sym_plain,
  [564] = 2,
    ACTIONS(175), 3,
      ts_builtin_sym_end,
      sym_version,
      sym__blank,
    ACTIONS(177), 4,
      sym__bodiless_method,
      sym__body_method,
      sym_header_name,
      sym_plain,
  [576] = 2,
    ACTIONS(179), 3,
      ts_builtin_sym_end,
      sym_version,
      sym__blank,
    ACTIONS(181), 4,
      sym__bodiless_method,
      sym__body_method,
      sym_header_name,
      sym_plain,
  [588] = 2,
    ACTIONS(183), 3,
      ts_builtin_sym_end,
      sym_version,
      sym__blank,
    ACTIONS(185), 4,
      sym__bodiless_method,
      sym__body_method,
      sym_header_name,
      sym_plain,
  [600] = 1,
    ACTIONS(187), 5,
      ts_builtin_sym_end,
      sym__bodiless_method,
      sym__body_method,
      sym_version,
      sym__blank,
  [608] = 1,
    ACTIONS(189), 5,
      ts_builtin_sym_end,
      sym__bodiless_method,
      sym__body_method,
      sym_version,
      sym__blank,
  [616] = 1,
    ACTIONS(191), 5,
      ts_builtin_sym_end,
      sym__bodiless_method,
      sym__body_method,
      sym_version,
      sym__blank,
  [624] = 1,
    ACTIONS(193), 5,
      ts_builtin_sym_end,
      sym__bodiless_method,
      sym__body_method,
      sym_version,
      sym__blank,
  [632] = 1,
    ACTIONS(195), 5,
      ts_builtin_sym_end,
      sym__bodiless_method,
      sym__body_method,
      sym_version,
      sym__blank,
  [640] = 1,
    ACTIONS(197), 5,
      ts_builtin_sym_end,
      sym__bodiless_method,
      sym__body_method,
      sym_version,
      sym__blank,
  [648] = 5,
    ACTIONS(199), 1,
      aux_sym_trailer_token1,
    ACTIONS(201), 1,
      sym_status_code,
    ACTIONS(203), 1,
      sym__ws,
    ACTIONS(205), 1,
      sym__eol,
    STATE(74), 1,
      sym_status_text,
  [664] = 1,
    ACTIONS(207), 5,
      ts_builtin_sym_end,
      sym__bodiless_method,
      sym__body_method,
      sym_version,
      sym__blank,
  [672] = 1,
    ACTIONS(209), 5,
      ts_builtin_sym_end,
      sym__bodiless_method,
      sym__body_method,
      sym_version,
      sym__blank,
  [680] = 4,
    ACTIONS(211), 1,
      sym_value_text,
    ACTIONS(213), 1,
      sym__ws,
    ACTIONS(215), 1,
      sym__eol,
    STATE(66), 1,
      sym_value,
  [693] = 4,
    ACTIONS(217), 1,
      sym_version,
    ACTIONS(219), 1,
      aux_sym_trailer_token1,
    ACTIONS(221), 1,
      sym__eol,
    STATE(58), 1,
      sym_trailer,
  [706] = 4,
    ACTIONS(223), 1,
      aux_sym_trailer_token1,
    ACTIONS(225), 1,
      sym__ws,
    ACTIONS(227), 1,
      sym__eol,
    STATE(65), 1,
      sym_status_text,
  [719] = 4,
    ACTIONS(211), 1,
      sym_value_text,
    ACTIONS(229), 1,
      sym__ws,
    ACTIONS(231), 1,
      sym__eol,
    STATE(62), 1,
      sym_value,
  [732] = 3,
    ACTIONS(215), 1,
      sym__eol,
    ACTIONS(233), 1,
      sym_value_text,
    STATE(66), 1,
      sym_value,
  [742] = 3,
    ACTIONS(235), 1,
      sym_url_text,
    STATE(10), 1,
      sym__request_line,
    STATE(53), 1,
      sym_target,
  [752] = 3,
    ACTIONS(233), 1,
      sym_value_text,
    ACTIONS(237), 1,
      sym__eol,
    STATE(75), 1,
      sym_value,
  [762] = 3,
    ACTIONS(235), 1,
      sym_url_text,
    STATE(6), 1,
      sym__request_line,
    STATE(53), 1,
      sym_target,
  [772] = 3,
    ACTIONS(239), 1,
      sym__ws,
    ACTIONS(241), 1,
      sym__eol,
    STATE(61), 1,
      sym__status_line_tail,
  [782] = 2,
    ACTIONS(243), 1,
      sym__ws,
    ACTIONS(245), 1,
      sym__eol,
  [789] = 2,
    ACTIONS(247), 1,
      anon_sym_COLON,
    ACTIONS(249), 1,
      sym__ws,
  [796] = 2,
    ACTIONS(223), 1,
      aux_sym_trailer_token1,
    STATE(69), 1,
      sym_status_text,
  [803] = 2,
    ACTIONS(251), 1,
      sym__ws,
    ACTIONS(253), 1,
      sym__eol,
  [810] = 1,
    ACTIONS(255), 2,
      sym__eol,
      sym__ws,
  [815] = 2,
    ACTIONS(257), 1,
      sym__ws,
    ACTIONS(259), 1,
      sym__eol,
  [822] = 2,
    ACTIONS(223), 1,
      aux_sym_trailer_token1,
    STATE(72), 1,
      sym_status_text,
  [829] = 1,
    ACTIONS(261), 2,
      sym__eol,
      sym__ws,
  [834] = 1,
    ACTIONS(263), 1,
      sym__eol,
  [838] = 1,
    ACTIONS(265), 1,
      sym__eol,
  [842] = 1,
    ACTIONS(267), 1,
      sym__eol,
  [846] = 1,
    ACTIONS(269), 1,
      sym__ws,
  [850] = 1,
    ACTIONS(271), 1,
      sym__eol,
  [854] = 1,
    ACTIONS(273), 1,
      sym__eol,
  [858] = 1,
    ACTIONS(275), 1,
      sym__ws,
  [862] = 1,
    ACTIONS(277), 1,
      sym__eol,
  [866] = 1,
    ACTIONS(279), 1,
      sym__eol,
  [870] = 1,
    ACTIONS(281), 1,
      sym__eol,
  [874] = 1,
    ACTIONS(283), 1,
      ts_builtin_sym_end,
  [878] = 1,
    ACTIONS(285), 1,
      sym__eol,
  [882] = 1,
    ACTIONS(287), 1,
      anon_sym_COLON,
  [886] = 1,
    ACTIONS(289), 1,
      sym__eol,
  [890] = 1,
    ACTIONS(291), 1,
      sym__eol,
  [894] = 1,
    ACTIONS(293), 1,
      sym__eol,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 28,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 81,
  [SMALL_STATE(6)] = 106,
  [SMALL_STATE(7)] = 131,
  [SMALL_STATE(8)] = 156,
  [SMALL_STATE(9)] = 181,
  [SMALL_STATE(10)] = 206,
  [SMALL_STATE(11)] = 226,
  [SMALL_STATE(12)] = 246,
  [SMALL_STATE(13)] = 266,
  [SMALL_STATE(14)] = 287,
  [SMALL_STATE(15)] = 308,
  [SMALL_STATE(16)] = 329,
  [SMALL_STATE(17)] = 350,
  [SMALL_STATE(18)] = 371,
  [SMALL_STATE(19)] = 392,
  [SMALL_STATE(20)] = 408,
  [SMALL_STATE(21)] = 424,
  [SMALL_STATE(22)] = 436,
  [SMALL_STATE(23)] = 452,
  [SMALL_STATE(24)] = 464,
  [SMALL_STATE(25)] = 476,
  [SMALL_STATE(26)] = 488,
  [SMALL_STATE(27)] = 500,
  [SMALL_STATE(28)] = 512,
  [SMALL_STATE(29)] = 528,
  [SMALL_STATE(30)] = 540,
  [SMALL_STATE(31)] = 552,
  [SMALL_STATE(32)] = 564,
  [SMALL_STATE(33)] = 576,
  [SMALL_STATE(34)] = 588,
  [SMALL_STATE(35)] = 600,
  [SMALL_STATE(36)] = 608,
  [SMALL_STATE(37)] = 616,
  [SMALL_STATE(38)] = 624,
  [SMALL_STATE(39)] = 632,
  [SMALL_STATE(40)] = 640,
  [SMALL_STATE(41)] = 648,
  [SMALL_STATE(42)] = 664,
  [SMALL_STATE(43)] = 672,
  [SMALL_STATE(44)] = 680,
  [SMALL_STATE(45)] = 693,
  [SMALL_STATE(46)] = 706,
  [SMALL_STATE(47)] = 719,
  [SMALL_STATE(48)] = 732,
  [SMALL_STATE(49)] = 742,
  [SMALL_STATE(50)] = 752,
  [SMALL_STATE(51)] = 762,
  [SMALL_STATE(52)] = 772,
  [SMALL_STATE(53)] = 782,
  [SMALL_STATE(54)] = 789,
  [SMALL_STATE(55)] = 796,
  [SMALL_STATE(56)] = 803,
  [SMALL_STATE(57)] = 810,
  [SMALL_STATE(58)] = 815,
  [SMALL_STATE(59)] = 822,
  [SMALL_STATE(60)] = 829,
  [SMALL_STATE(61)] = 834,
  [SMALL_STATE(62)] = 838,
  [SMALL_STATE(63)] = 842,
  [SMALL_STATE(64)] = 846,
  [SMALL_STATE(65)] = 850,
  [SMALL_STATE(66)] = 854,
  [SMALL_STATE(67)] = 858,
  [SMALL_STATE(68)] = 862,
  [SMALL_STATE(69)] = 866,
  [SMALL_STATE(70)] = 870,
  [SMALL_STATE(71)] = 874,
  [SMALL_STATE(72)] = 878,
  [SMALL_STATE(73)] = 882,
  [SMALL_STATE(74)] = 886,
  [SMALL_STATE(75)] = 890,
  [SMALL_STATE(76)] = 894,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_response, 2, 0, 3),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_response, 2, 0, 3),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_response, 3, 0, 3),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_response, 3, 0, 3),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__body_request, 3, 0, 4),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__body_request, 3, 0, 4),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_response, 3, 0, 7),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_response, 3, 0, 7),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_response, 4, 0, 7),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_response, 4, 0, 7),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__body_request, 4, 0, 4),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__body_request, 4, 0, 4),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bodiless_request, 3, 0, 4),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__bodiless_request, 3, 0, 4),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bodiless_request, 4, 0, 4),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__bodiless_request, 4, 0, 4),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__bodiless_request_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__bodiless_request_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bodiless_request_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bodiless_request_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__body_request, 5, 0, 4),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__body_request, 5, 0, 4),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_response, 5, 0, 7),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_response, 5, 0, 7),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_response, 4, 0, 3),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_response, 4, 0, 3),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__body_request_repeat1, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__body_request_repeat1, 2, 0, 0),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__body_request_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 13),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 3, 0, 13),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__request_line, 2, 0, 8),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__request_line, 2, 0, 8),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__request_line, 4, 0, 17),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__request_line, 4, 0, 17),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__request_line, 4, 0, 8),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__request_line, 4, 0, 8),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 4, 0, 13),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 4, 0, 13),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 4, 0, 19),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 4, 0, 19),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__request_line, 3, 0, 8),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__request_line, 3, 0, 8),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__request_line, 5, 0, 17),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__request_line, 5, 0, 17),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__request_line, 5, 0, 8),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__request_line, 5, 0, 8),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 5, 0, 21),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 5, 0, 21),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 5, 0, 13),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 5, 0, 13),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 6, 0, 22),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 6, 0, 22),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_response, 6, 0, 20),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_response, 4, 0, 9),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 1, 0, 1),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 1, 0, 2),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__body_request, 5, 0, 12),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_response, 5, 0, 14),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__status_line_tail, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__body_request, 6, 0, 18),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_response, 5, 0, 16),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__status_line_tail, 2, 0, 5),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trailer, 1, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target, 1, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__status_line_tail, 3, 0, 10),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_status_text, 1, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__status_line_tail, 4, 0, 15),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__status_line_tail, 3, 0, 11),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__status_line_tail, 2, 0, 6),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__eol = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__eol] = sym__eol,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__eol] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_http_message_external_scanner_create(void);
void tree_sitter_http_message_external_scanner_destroy(void *);
bool tree_sitter_http_message_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_http_message_external_scanner_serialize(void *, char *);
void tree_sitter_http_message_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_http_message(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_http_message_external_scanner_create,
      tree_sitter_http_message_external_scanner_destroy,
      tree_sitter_http_message_external_scanner_scan,
      tree_sitter_http_message_external_scanner_serialize,
      tree_sitter_http_message_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
